const main = async() => {
  console.log("Hello world!")
}

main().catch(console.error)

